### ISSUE TITLE
AndroidX compatibility : Migrating to AndroidX

### ISSUE THREAD

**Issue by faisalramdan-id** [PonnamKarthik/FlutterYoutube#33]
As we are not sure when this will be merged, you can adjust your `pubspec.yaml` in the meantime:

```
flutter_youtube:
    git:
      url: https://github.com/faisalramdan17/FlutterYoutube.git
      ref: android-x
```

_Originally posted by @faisalramdan17 in https://github.com/PonnamKarthik/FlutterYoutube/pull/32#issuecomment-465854092_
